url: https://TENET-RCCPII/CarpentryConnect-Johannesburg-2018
baseurl: "/"

# Site settings
title: CarpentryConnnect Johannesburg 2018 
email: carpentryconnect-jhb-2018@googlegroups.com
description: "The official website for CarpentryConnect-Johannesburg 2018 in Johannesburg, South Africa"



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/
#  - title: github
#    url: https://github.com/carpentries/
#  - title: facebook
#    url: https://www.facebook.com/carpentries/
#  - title: slack
#    url: https://swc-slack-invite.herokuapp.com/

# Postal address (add as many lines as necessary)
#address:
#  - line: Brisbane, Australia

# Build settings
markdown: kramdown
permalink: pretty
